= Documentación Cirrus CRM

== Requerimientos Funcionales.

1. El sistema debe permitir incorporar varias empresas del mismo Grupo (o Holding), para esto debe permitir identificar a cada usuario como miembro de una empresa en particular, en este sentido un Grupo tendría varias Empresas y una Empresa tendría varios Empleados. Donde cada empleado contará con al menos la siguiente información Nombres, Apellidos, Correo Electrónico, Cargo, Código Empleado.

[plantuml]
----
@startuml
class Grupo {
    - nombre: string
    - empresas: List<Empresa>

    + agregarEmpresa(empresa: Empresa): void
    + eliminarEmpresa(empresa: Empresa): void
}

class Empresa {
    - nombre: string
    - empleados: List<Empleado>

    + agregarEmpleado(empleado: Empleado): void
    + eliminarEmpleado(empleado: Empleado): void
}

class Empleado {
    - nombres: string
    - apellidos: string
    - correoElectronico: string
    - cargo: string
    - codigoEmpleado: string

    + getNombres(): string
    + getApellidos(): string
    + getCorreoElectronico(): string
    + getCargo(): string
    + getCodigoEmpleado(): string
}

Grupo "1" *-- "*" Empresa
Empresa "1" *-- "*" Empleado

@enduml
----

== Requerimientos No Funcionales.

1. La autenticación debe realizarse utilizando el Active Directory de cada empresa, en general cada una de las empresas tiene su propio Active Directory, para conseguir esto se utilizará el concepto de Federación de Usuarios y la herramienta Keycloak.



